### ISSUE TITLE
Support renewing material in mylibrary

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/mylibrary#735]

**Comment by thatbudakguy** [comment]
this ticket is mostly just to confirm the API functions how it says it does and isn't broken.

**Comment by jcoyne** [comment]
I attemped to use the API to renew a record and I get a timeout:
```
irb(main):001:0> client = FolioClient.new
=>
#<FolioClient:0x000000010ba94988
...
irb(main):002:0> user_id = client.lookup_user_id('jcoyne85')
=> "562a5cb0-e998-4ea2-80aa-34ac2b536238"
irb(main):003:0> client.renew_item(user_id, '1a4280f5-a917-589d-8d1c-b6f915667f0e')
/Users/jcoyne85/workspace/sul-dlss/mylibrary/app/services/folio_client.rb:59:in `check_response': Renew request for user_id: 562a5cb0-e998-4ea2-80aa-34ac2b536238, item_id: 1a4280f5-a917-589d-8d1c-b6f915667f0e was not successful. status: 500, io.vertx.core.http.impl.NoStackTraceTimeoutException: The timeout period of 5000ms has been exceeded while executing POST /circulation/renew-by-id for server okapi:9130 (RuntimeError)
```

**Comment by thatbudakguy** [comment]
work merged in https://github.com/sul-dlss/mylibrary/pull/795 but unclear if it's working

**Comment by corylown** [comment]
I think this is working. I was able to renew a couple of items using `client.renew_item` and then got sensible error messages in cases when the item could not be renewed:

**Successful item renewal:**

```
irb(main):006:0> client.renew_item('e8cf1192-7de7-4bb0-880e-3c985f718e96','abe9a6df-b3cf-50c9-a64b-4cdb8b3228c9')
=> nil
```


![Image](https://github.com/sul-dlss/mylibrary/assets/458247/91945ee2-86d9-4cf6-a612-e53f0811a2f8)


```
irb(main):007:0> client.renew_item('e8cf1192-7de7-4bb0-880e-3c985f718e96','abe9a6df-b3cf-50c9-a64b-4cdb8b3228c9')
/Users/corylown/workspace/mylibrary/app/services/folio_client.rb:175:in `check_response': Renew request for user_id: e8cf1192-7de7-4bb0-880e-3c985f718e96, item_id: abe9a6df-b3cf-50c9-a64b-4cdb8b3228c9 was not successful. status: 422, { (RuntimeError)
  "errors" : [ {
    "message" : "renewal would not change the due date",
    "parameters" : [ {
      "key" : "loanPolicyName",
      "value" : "1yearfixed-2renew-14daygrace"
    }, {
      "key" : "loanPolicyId",
      "value" : "ad47ac4d-8305-4039-8ac4-93a69a789074"
    } ],
    "overridableBlock" : {
      "name" : "renewalDueDateRequiredBlock",
      "missingPermissions" : [ "circulation.override-renewal-block" ]
    }
  } ]
}
```

**Blocked account**

```
irb(main):009:0> client.renew_item('cceb6a9c-7892-4b09-9e00-1fa891d0bf20','b3aa7473-9940-55d1-adc9-e80ecbfcb536')
/Users/corylown/workspace/mylibrary/app/services/folio_client.rb:175:in `check_response': Renew request for user_id: cceb6a9c-7892-4b09-9e00-1fa891d0bf20, item_id: b3aa7473-9940-55d1-adc9-e80ecbfcb536 was not successful. status: 422, { (RuntimeError)
  "errors" : [ {
    "message" : "You have fees and fines to pay. Your account is blocked.",
    "parameters" : [ ],
    "overridableBlock" : {
      "name" : "patronBlock",
      "missingPermissions" : [ "circulation.override-patron-block" ]
    }
  } ]
}
```

**loan at maximum renewal**

```
irb(main):010:0> client.renew_item('3e072aa7-d74a-4c17-9d30-416d75f7971a','2bf7acc3-45b9-5697-921e-4ab5798e39b2')
/Users/corylown/workspace/mylibrary/app/services/folio_client.rb:175:in `check_response': Renew request for user_id: 3e072aa7-d74a-4c17-9d30-416d75f7971a, item_id: 2bf7acc3-45b9-5697-921e-4ab5798e39b2 was not successful. status: 422, { (RuntimeError)
  "errors" : [ {
    "message" : "loan at maximum renewal number",
    "parameters" : [ {
      "key" : "loanPolicyName",
      "value" : "1yearfixed-2renew-14daygrace"
    }, {
      "key" : "loanPolicyId",
      "value" : "ad47ac4d-8305-4039-8ac4-93a69a789074"
    } ],
    "overridableBlock" : {
      "name" : "renewalBlock",
      "missingPermissions" : [ "circulation.override-renewal-block" ]
    }
  } ]
}
```

**Comment by cbeer** [comment]
Sure, but I I don't think any of the renew buttons the user sees work?
